#!/usr/bin/env ruby
# frozen_string_literal: true
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'gum'
end

require "json"
require 'open3'
require 'fileutils'

CACHE_DIR = File.join(ENV['XDG_CACHE_HOME'] || File.expand_path('~/.cache'), 'kubecon')
NAMESPACES = File.join(CACHE_DIR, "namespaces")
HISTORY_PATH = File.join(CACHE_DIR, "history")

FileUtils.mkdir_p(CACHE_DIR)

def kubectl(title = "Running...", *cmd)
  result = Gum.spin(title, spinner: :line) do
    IO.popen(['kubectl', '-o', 'json'] + cmd).read
  end
  result
end

def kubectl_setup?
  _stdout, stderr, status = Open3.capture3("kubectl config get-contexts")

  unless status.success?
    puts stderr
    exit status.exitstatus
  end
end

def namespaces
  return JSON.parse(File.read(NAMESPACES), symbolize_names: true)[:items] if File.exist?(NAMESPACES)

  namespaces = kubectl("Getting namespaces", "get", "namespaces")
  File.open(NAMESPACES, "w") do |f|
    f.write(namespaces)
  end
end

def deployments(namespace)
  kubectl("Getting deployments for #{namespace}", "get", "deployments", "-n", namespace)
end

def choose_with_history(items, keys, header)
  items = items.is_a?(String) ? JSON.parse(items, symbolize_names: true)[:items] : items

  history = File.exist?(HISTORY_PATH) ? JSON.parse(File.read(HISTORY_PATH), symbolize_names: true) : {}

  names = items.first.is_a?(Hash) ? items.map { |i| i.dig(:metadata, :name) }.compact : items
  hist = history.dig(*keys) || []

  selected = Gum.filter((hist.reverse + names).uniq, header: header)

  keys[0..-2].reduce(history) { |h, k| h[k] ||= {} }[keys.last] = (hist + [selected]).uniq
  File.write(HISTORY_PATH, JSON.pretty_generate(history))
  selected
end

namespace = choose_with_history(namespaces, [:namespaces], "Choose a namespace")
exit 1 if namespace.nil?

deployment = choose_with_history(deployments(namespace), [:deployments, namespace], "Choose a deployment for #{namespace}")
exit 1 if deployment.nil?

command = Gum.input(value: "rails c", placeholder: "Enter a command to run", prompt: "> ")
exit 1 if command.nil?

command_style = Gum.style(command, foreground: "212")
pod_style = Gum.style("#{deployment} (#{namespace})", foreground: "212")

box = Gum.style(
  "Running #{command_style} on #{pod_style}",
  height: 3,
  padding: "1 2",
  border: :double,
  border_foreground: "57"
)

puts box

args = ['kubectl', 'exec', '-it', '-n', namespace, "deploy/#{deployment}", '--']
args.concat(command.is_a?(Array) ? command : Shellwords.split(command))
system(*args)
